const fs = require("node:fs");
const path = require("node:path");
const { withDangerousMod } = require("@expo/config-plugins");

const POST_INSTALL_MARKER = "# @generated by withIosXcode26Fix";

function patchPodfile(contents) {
  let patched = contents;

  if (!patched.includes(POST_INSTALL_MARKER)) {
    const postInstallEnd = "  end\nend";
    const insertionPoint = patched.lastIndexOf(postInstallEnd);
    if (insertionPoint === -1) {
      throw new Error("Could not find the end of the Expo post_install block in the iOS Podfile");
    }

    const postInstallBlock = `
    ${POST_INSTALL_MARKER}
    # glog 0.3.5 includes these headers from inside namespace google. Marking
    # them textual prevents Xcode 26 from importing submodules in a namespace.
    glog_modulemap = File.join(
      installer.sandbox.root.to_s,
      'Target Support Files',
      'glog',
      'glog.modulemap'
    )
    glog_textual_headers = <<~'GLOG_TEXTUAL_HEADERS'
        textual header "glog/log_severity.h"
        textual header "glog/vlog_is_on.h"
    GLOG_TEXTUAL_HEADERS

    if File.exist?(glog_modulemap)
      modulemap_contents = File.read(glog_modulemap)
      unless modulemap_contents.include?(glog_textual_headers)
        umbrella = '  umbrella header "glog-umbrella.h"'
        unless modulemap_contents.include?(umbrella)
          raise 'Could not find the glog umbrella header in its module map'
        end
        modulemap_contents = modulemap_contents.sub(
          umbrella,
          "#{umbrella}\\n#{glog_textual_headers.rstrip}"
        )
        File.write(glog_modulemap, modulemap_contents)
      end
    end

    # Apple Clang in Xcode 26 enforces fmt consteval rules that these bundled
    # React Native dependencies do not satisfy when compiled as C++20.
    installer.pods_project.targets.each do |target|
      next unless ['fmt', 'glog'].include?(target.name)

      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
`;
    patched = `${patched.slice(0, insertionPoint)}${postInstallBlock}${patched.slice(insertionPoint)}`;
  }

  return patched;
}

const withIosXcode26Fix = (config) =>
  withDangerousMod(config, [
    "ios",
    async (modConfig) => {
      const podfilePath = path.join(modConfig.modRequest.platformProjectRoot, "Podfile");
      const contents = fs.readFileSync(podfilePath, "utf8");
      fs.writeFileSync(podfilePath, patchPodfile(contents));
      return modConfig;
    },
  ]);

module.exports = withIosXcode26Fix;
module.exports.patchPodfile = patchPodfile;
