version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: cajero-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cajero_db
    ports:
      - "5432:5432"
    volumes:
      - cajero-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Auto-runs on first startup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cajero_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  cajero-spring:
    build: .
    image: cajero-spring
    container_name: cajero-spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cajero_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  cajero-data:
