spring:
  datasource:
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

swagger:
  username: ${SWAGGER_USERNAME:admin} # Default fallback
  password: ${SWAGGER_PASSWORD:admin} # Default fallback
