server:
  port: ${BACKEND_PORT}
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  profiles:
    active: dev
  datasource:
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-ms: ${JWT_EXPIRATION_MS}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

swagger:
  username: ${SWAGGER_USERNAME}
  password: ${SWAGGER_PASSWORD}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
