name: Build and Deploy Cajero Backend

on:
  push:
    branches:
      - dev
      # - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy container
        run: |
          TAG=${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
          docker run \
            -e DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e JWT_EXPIRATION_MS=${{ secrets.JWT_EXPIRATION_MS }} \
            -e SWAGGER_USERNAME=${{ secrets.SWAGGER_USERNAME }} \
            -e SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }} \
            -e ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
            -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
            fidelisyugita/cajero-backend:${TAG}

      - name: Build Docker image
        run: |
          cd backend
          TAG=${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
          docker build --platform=linux/amd64 -t fidelisyugita/cajero-backend:$TAG .
          docker push fidelisyugita/cajero-backend:$TAG

      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            TAG=${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
            docker pull fidelisyugita/cajero-backend:$TAG
            docker stop cajero-backend || true
            docker rm cajero-backend || true
            docker run -d --name cajero-backend -p 80:8080 fidelisyugita/cajero-backend:$TAG
