name: Build and Deploy Cajero Backend

on:
  push:
    branches: [dev-fe]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ✅ Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cajero-frontend:dev
          platforms: linux/amd64,linux/arm64

      # ✅ Deploy to Oracle VM
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # ---- Frontend ----
            docker pull ${{ secrets.DOCKER_USERNAME }}/cajero-frontend:dev
            docker stop cajero-frontend || true
            docker rm cajero-frontend || true
            docker run -d --name cajero-frontend \
              -e VITE_API_URL=${{ secrets.VITE_API_URL }} \
              -p 5173:5173 \
              ${{ secrets.DOCKER_USERNAME }}/cajero-frontend:dev
