name: Build and Deploy Cajero Backend

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy container
        run: |
          docker run \
            -e DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e JWT_EXPIRATION_MS=${{ secrets.JWT_EXPIRATION_MS }} \
            -e SWAGGER_USERNAME=${{ secrets.SWAGGER_USERNAME }} \
            -e SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }} \
            -e ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
            -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
            fidelisyugita/cajero-backend:dev

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: fidelisyugita/cajero-backend:dev
          platforms: linux/amd64

      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            docker pull fidelisyugita/cajero-backend:dev
            docker stop cajero-backend || true
            docker rm cajero-backend || true
            docker run -d --name cajero-backend -p 80:8080 fidelisyugita/cajero-backend:dev
